Add database
MaXM91/java-filmorate pull request #21
Opened 2023-09-06 15:38 UTC by MaXM91

2023-09-10 09:06 UTC, NikolaiDem requested changes

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @NotBlank(message = "film: name is blank!")
NotBlank включает в себя NotEmpty

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, List<Genre> genres, Mpa mpa, Integer rate,
Вместо шаблонного кода можно использовать lombok

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private HashMap<Integer, Boolean> userFriends = new HashMap<>();
Для чего нужен Map вместо Set?

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>      public Film create(Film film) throws ValidationException {
throws для Runtime исключений избыточен. Аналогично для остальных методов

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private List<Genre> changeFilmGenre(Film film) {
Можно проще:
1) избавиться от выполнения contains
2) избавиться от множественных запросов в БД

Например, 
    private List<Genre> changeFilmGenre(Film film) {
        List<Genre> uniqueGenres = film.getGenres().stream()
                .distinct()
                .collect(Collectors.toList());

        jdbcTemplate.batchUpdate(
                "INSERT INTO film_genre (film_id, genre_id) VALUES(?,?)",
                new BatchPreparedStatementSetter() {
                    public void setValues(PreparedStatement ps, int i) throws SQLException {
                        ps.setLong(1, film.getId());
                        ps.setLong(2, uniqueGenres.get(i).getId());
                    }

                    public int getBatchSize() {
                        return uniqueGenres.size();
                    }
                });

        return jdbcTemplate.query("SELECT * FROM genre g join film_genre fg on g.genre_id = fg.genre_id WHERE fg.film_id = ?",
                (rs, rowNum) -> new Genre(rs.getInt("genre_id"), rs.getString("name")),
                film.getId());
    }

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException exc) {
Перехватывать RuntimeException - плохая практика. То есть несмотря на любую поломку программы, считаем, что просто не найден пользователь, что неверно. 
Лучше конкретизировать тип исключения, который может быть брошен методом queryForObject.
Аналогично для остальных методов

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> get() {
По названию get непонятно, что он возвращает)

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                rs.getString("description"), readFilmGenre(rs.getInt("id")),
Методы readFilmGenre и readUsersLike создают проблему N+1 запроса.
Пусть всего в БД находится 1 000 000 фильмов.
Запросом SELECT * FROM films получим все 1 000 000 фильмов за одно обращение к БД. 
А чтобы заполнить жанры и лайки, нужно выполнить еще 1 000 000 запросов для жанров и 1 000 000 запросов для лайков.
Получим 2 000 000 + 1 запросов в БД. А хотим ограничиться только 1 + 2 запросами )
Аналогично для popularFilms

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return null;
null лучше не возвращать, если есть такая возможность. Можно заменить на пустой список.
Аналогично для остальных методов

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "SELECT fg.genre_id, g.name \n" + "FROM films AS f\n" +
Использование films здесь лишнее

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    if (rs.getInt("genre_id") == 0) {
0 в каком случае будет?

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        } catch (RuntimeException exc) {
RuntimeException лучше заменить на более детализированное исключение. 
При формировании ObjectNotFoundException лучше указать id, по которому ничего не найдено

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public LikeDbStorage(JdbcTemplate jdbcTemplate) {
Шаблонный код можно заменить lombok-ом. Аналогично в остальных классах

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        } catch (RuntimeException ecx) {
RuntimeException лучше заменить на более детализированное исключение. 
При формировании ObjectNotFoundException лучше указать id, по которому ничего не найдено

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                assert user != null;
Для чего assert в каждой итерации, при том, что ссылка на user не меняется?

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                user.setUserFriends(friendId);
Можно установить всех друзей без цикла?

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            List<Integer> friends = foundFriendsIds(rs.getInt("id"));
Здесь проблема N+1 запроса аналогично жанрам и лайкам

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (Integer idFriend : friendsIds) {
Лучше получить всех друзей одним запросом вместо использования цикла

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        jdbcTemplate.update("INSERT INTO friends (user_id_from, user_id_to) VALUES(?,?)", id, idFriend);
А если отправить 1 000 000 запросов подряд на добавление юзером 1 юзера 2, как будет обработана ошибка БД?

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            jdbcTemplate.update("UPDATE friends SET approved_by_to = 1 WHERE user_id_from = ? AND user_id_to = ?", id,
В чем профит иметь на каждую дружбу по 2 записи и еще статус дружбы? Статус тогда выглядит лишним

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            if (friendsOtherId.contains(user)) {
Пересечение друзей можно попробовать сделать на уровне запроса через джойны

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (User user : checkFriend) {
Проверку можно сделать на уровне запроса

2023-09-10 09:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmCombinedSerializer.java
> +public class FilmCombinedSerializer {
Закомментированный код лишний

2023-09-22 22:31 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private HashMap<Integer, Boolean> userFriends = new HashMap<>();
В предыдущей реализации интерфейса вроде как надо было просто держать список добавленных друзей, в этой реализации необходимо хранить подтверждение дружбы. Что должно быть в объекте не указанно, просто друзья или друзья подтвержденные, или все друзья которых добавил со статусом подтверждения - не указано. Верну обратно на SET, буду загружать только друзей, которых добавил. Посмотрю как пройдут тесты...

2023-09-26 23:23 UTC, NikolaiDem requested changes

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/ObjectFilm.java
> +public class ObjectFilm {
Не используется

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film delete(Integer id) {
лучше добавить валидацию в контроллер, избавившись от лишнего  кода,
 добавив Positive перед id
Пример
    @DeleteMapping("/{id}")
    public Film deleteFilm(@PathVariable @Positive Integer id) {
        return filmService.delete(id);
    }
И еще на уровень контроллера нужно добавить Validated, чтобы эти аннотации обработались.
Аналогично для остальных методов и сервисов

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>          if (filmStorage.found(film.getId()) == null) {
Довольно много дублирующегося кода вида
if (  == null) {
throw new Exception(...);
}
Лучше вынести повторяющийся код в отдельные методы

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      @PutMapping("/{id}/like/{userId}")
Лучше использовать напрямую likeService для добавления и удаления лайка

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
>          if (user == null) {
Довольно много дублирующегося кода вида
if ( == null) {
throw new Exception(...);
}
Лучше вынести повторяющийся код в отдельные методы

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    FilmDbStorage.this.readGenre(rs.getInt("id")), FilmDbStorage.this.readMpa(rs.getInt("id")),
Использование имени класса (FilmDbStorage....readeGenres) для нестатических методов избыточно

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    FilmDbStorage.this.readGenre(rs.getInt("id")), FilmDbStorage.this.readMpa(rs.getInt("id")),
FilmDbStorage.this.readGenre(rs.getInt("id")) получение жанров создает проблему N+1 запроса, так как появляется необходимость для каждого фильма идти в БД. Необходимо получить все жанры за один запрос в БД сразу для всех фильмов

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    FilmDbStorage.this.readGenre(rs.getInt("id")), FilmDbStorage.this.readMpa(rs.getInt("id")),
mpa можно добавить непосредственно в sql запрос, чтобы снова не ходить в БД

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    rs.next();
rs.next() можно вынести за пределы if/else

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre found(Integer id) {
Методы очень сильно дублируются

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public void add(Integer filmId, Integer userId) {
Методы очень сильно дублируются

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    public Mpa found(Integer id) {
Методы очень сильно дублируются

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_mpa
Какая связь предполагается между film и mpa? Если не many-to-many, то для чего создана отдельная таблица? Можно mpa_id хранить в фильме

2023-09-26 23:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                    "WHERE f.user_id_from = ? AND f.user_id_to IN (SELECT user_id_to\n" +
При использовании 2х джойнов вложенный селект здесь явно лишний

2023-09-28 22:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/ObjectFilm.java
> +public class ObjectFilm {
удалено

2023-09-28 22:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      @PutMapping("/{id}/like/{userId}")
введено

2023-09-29 00:15 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    public Mpa found(Integer id) {
Вынесен общий private метод

2023-09-29 00:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public void add(Integer filmId, Integer userId) {
Вынесен общий private метод

2023-09-29 00:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre found(Integer id) {
Вынесен общий private метод

2023-09-29 00:19 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film delete(Integer id) {
При введении валидации, SBV отправляет 400 ошибку. На примере удаления лайка с отрицательным ид, наблюдаем требование к обработке и определению как 404 ошибки.

2023-09-29 07:28 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return null;
исправлено

2023-09-29 07:29 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private List<Genre> changeFilmGenre(Film film) {
исправлено

2023-09-29 07:30 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "SELECT fg.genre_id, g.name \n" + "FROM films AS f\n" +
метод удален

2023-09-29 07:33 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    if (rs.getInt("genre_id") == 0) {
Где-то читал, при отсутствии данных-> int - 0, String - null.

2023-09-29 07:36 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        } catch (RuntimeException exc) {
исправлено

2023-09-29 07:37 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public LikeDbStorage(JdbcTemplate jdbcTemplate) {
исправлено

2023-09-29 07:37 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        } catch (RuntimeException ecx) {
исправлено

2023-09-29 07:38 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                assert user != null;
исправлено

2023-09-29 07:38 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                user.setUserFriends(friendId);
исправлено

2023-09-29 07:39 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            List<Integer> friends = foundFriendsIds(rs.getInt("id"));
исправлено

2023-09-29 07:39 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (Integer idFriend : friendsIds) {
исправлено

2023-09-29 07:40 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            jdbcTemplate.update("UPDATE friends SET approved_by_to = 1 WHERE user_id_from = ? AND user_id_to = ?", id,
исправлено, статус исключен.

2023-09-29 07:41 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            if (friendsOtherId.contains(user)) {
исправлено

2023-09-29 07:41 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (User user : checkFriend) {
исправлено

2023-09-29 07:42 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmCombinedSerializer.java
> +public class FilmCombinedSerializer {
удалено

2023-09-29 07:45 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        jdbcTemplate.update("INSERT INTO friends (user_id_from, user_id_to) VALUES(?,?)", id, idFriend);
Добавлен контроль выбрасываемого методом update исключения

2023-09-29 07:53 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                rs.getString("description"), readFilmGenre(rs.getInt("id")),
исправлено

2023-09-29 07:54 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException exc) {
исправлено

2023-09-29 07:55 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
>          if (user == null) {
исправлено

2023-09-29 07:55 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>      public Film create(Film film) throws ValidationException {
исправлено

2023-09-29 07:56 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/ObjectFilm.java
> +    public ObjectFilm(int id) {
исправлено

2023-09-29 07:57 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public Mpa(int id, String name) {
исправлено

2023-09-29 07:57 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(Integer id, String name) {
исправлено

2023-09-30 19:40 UTC, MaXM91 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_mpa
Выполнено

2023-09-30 21:23 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>          if (filmStorage.found(film.getId()) == null) {
исправлено

2023-09-30 21:23 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                    "WHERE f.user_id_from = ? AND f.user_id_to IN (SELECT user_id_to\n" +
исправлено

2023-10-03 00:11 UTC, NikolaiDem requested changes

2023-10-03 00:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void checkIds(Integer id, String methodName) {
Для определения места возникновения исключения можно использовать StackTrace, передавать метод в исключение избыточно.
Аналогично для остальных сервисов

2023-10-03 00:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/like/LikeService.java
> +        if (filmId <= 0) {
Так как по требованиям нужно возвращать на отрицательный id 404 ошибку, это значит, что отрицательные id являются валидными, тогда проверки на 34 и 39 строках являются лишними

2023-10-03 00:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre found(Integer id) {
Можно сделать намного проще:
    public Genre found(Integer id) {
        List<Genre> genres = jdbcTemplate.query("SELECT * FROM genre where genre_id = ?", getGenreRowMapper(), id);
        if (genres.isEmpty()) {
            throw new ObjectNotFoundException(////////);
        }
        return genres.get(0);
    }

    public List<Genre> get() {
        return jdbcTemplate.query("SELECT * FROM genre", getGenreRowMapper());
    }

    private RowMapper<Genre> getGenreRowMapper() {
        return (rs, rowNum) -> new Genre(rs.getInt("genre_id"), rs.getString("genre_name"));
    }

Аналогично для mpa

2023-10-03 00:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        } catch (EmptyResultDataAccessException exc) {
Вместо всевозможных перехватов исключений лучше удостовериться, что они не возникнут, выполнив предварительные проверки.
Аналогично для остальных репозиториев

2023-10-03 00:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                    "LEFT JOIN friends AS fr ON u.id = fr.user_id_from \n" +
Для чего здесь 2-ой джойн?

2023-10-03 15:19 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/like/LikeService.java
> +        if (filmId <= 0) {
Исправлено

2023-10-03 18:38 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +package ru.yandex.practicum.filmorate.service.genre;
Исправлено

2023-10-03 20:59 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        } catch (EmptyResultDataAccessException exc) {
Исправлено. Отлавливание исключений оставлено на поисковых методах. (found(Integer id)), все остальные методы кроме getAll, getFriends и подобных проверятся методами found на сервисном уровне.

2023-10-03 21:25 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void checkIds(Integer id, String methodName) {
исправлено

2023-10-03 21:39 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                    "LEFT JOIN friends AS fr ON u.id = fr.user_id_from \n" +
2 джойн для того чтобы заполнить SET<Integer> с идами друзей у найденных друзей. В предыдущем модуле по тз заполняли список друзей. Тут реализую тоже. Находим простым запросом друзей пользователя ид, первым джойном получаем их данные, вторым джойном список ид их друзей. По полученным данным формируем List<User> друзей с полностью заполненной, необходимой информацией. Также выполняется в других запросах, где формируется объект User.

2023-10-03 21:50 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (response.size() == 0) {
Мы либо делаем так, либо получаем проблему n+2 запроса. Проблемы выдачи популярных фильмов как таковой нету. Делаем подзапрос фром, там же ставим лимит и собираем строки... Но мы ориентируемся на тесты, а по тестам фильм без лайков(т.е. фильм отсутствующий в таблице) тоже участвует в рейтинге, и тут простого запроса не получается, либо использовать то, что мы еще не проходили, или преобразовать столбцы в строку и все также писать дополнительный код для обработки. Выполнил так чтобы не было дополнительных запросов к БД и использовал уже вынесенную часть кода с других методов для формирования списка объектов.

2023-10-04 00:02 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            int num = (int) count * 2;
Переформировал sql запрос. Теперь все нормально

2023-10-04 00:03 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (response.size() == 0) {
Изменил sql запрос, тепрь этого нету

2023-10-04 22:13 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (ArrayIndexOutOfBoundsException exp) {
исправлено

2023-10-04 22:14 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                    "LEFT JOIN friends AS fr ON u.id = fr.user_id_from \n" +
для добавления ид друзей найденным друзьям

2023-10-04 22:14 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +        } catch (EmptyResultDataAccessException exc) {
исправлено

2023-10-04 22:15 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (response.size() == 0) {
исправлен запрос sql

2023-10-04 22:15 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            int num = (int) count * 2;
исправлен sql запрос

2023-10-04 22:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> get() {
исправлено

2023-10-04 22:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +package ru.yandex.practicum.filmorate.service.genre;
исправлено

2023-10-04 22:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/like/LikeService.java
> +        if (filmId <= 0) {
исправлено

2023-10-04 22:16 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void checkIds(Integer id, String methodName) {
исправлено

2023-10-04 23:43 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @NotBlank(message = "film: name is blank!")
исправлено

2023-10-04 23:44 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, List<Genre> genres, Mpa mpa, Integer rate,
исправлено

2023-10-04 23:47 UTC, MaXM91 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre found(Integer id) {
исправлено

2023-10-05 20:55 UTC, NikolaiDem approved these changes

2023-10-07 21:34 UTC, closed without merging